application: mahjonghand
version: 1
runtime: python
api_version: 1

handlers:
-  url: /stylesheets
   static_dir: stylesheets

-  url: /images
   static_dir: static/images

-  url: /.*
   script: main.py
   
